INSERT INTO DEVICE_TYPE VALUES(1, 'Windows');
INSERT INTO DEVICE_TYPE VALUES(2, 'Mac');

VALUES NEXT VALUE FOR SEQ_DEVICE_TYPE_KEY;
VALUES NEXT VALUE FOR SEQ_DEVICE_TYPE_KEY;

INSERT INTO DEVICE VALUES(1, 'Notebook', 1);
INSERT INTO DEVICE VALUES(2, 'PC', 2);

VALUES NEXT VALUE FOR SEQ_DEVICE_KEY;
VALUES NEXT VALUE FOR SEQ_DEVICE_KEY;

INSERT INTO SERVICE_DETAIL VALUES(1, true,  4, 'Device of any type', null);
INSERT INTO SERVICE_DETAIL VALUES(2, false, 5, 'Antivirus for Windows', 1);
INSERT INTO SERVICE_DETAIL VALUES(3, false, 7, 'Antivirus for Mac', 2);
INSERT INTO SERVICE_DETAIL VALUES(4, false, 3, 'Backup', null);
INSERT INTO SERVICE_DETAIL VALUES(5, false, 1, 'Screen Share', null);

VALUES NEXT VALUE FOR SEQ_SERVICE_DETAIL_KEY;
VALUES NEXT VALUE FOR SEQ_SERVICE_DETAIL_KEY;

INSERT INTO CUSTOMER VALUES(1, 'Customer One');

VALUES NEXT VALUE FOR SEQ_CUSTOMER_KEY;
VALUES NEXT VALUE FOR SEQ_CUSTOMER_KEY;
